#!/usr/bin/env php

<?php
/*
 ============ {IndoSec Framework} =============
	Coded By Arikun - IndoSec
	Tools : SubCalc (Subnet Calculator)
	Copyrigt (C) 2020 - Nii-san Hax0r
 
 ============ {IndoSec Framework} =============
*/

os();
error_reporting(0);
require 'agent/agent.php';

 function os()
 {
 	$os = PHP_OS;
 	if ($os = "linux") {
 		system("clear");
 	}elseif ($os = "windows") {
 		system("cls");
 	}
 }

function dataip($data)
{
	$getUserAgent = getUserAgent();
	
	$url = 'https://api.hackertarget.com/subnetcalc/?q='.$data;

	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_USERAGENT, $getUserAgent);

	$ex = curl_exec($ch);

	echo $ex;

}

function banner()
{
 echo "
    \ /
    oVo
\___XXX___/   Sub Calc V.0.1
 __XXXXX__    Crafted By Arikun - IndoSec
/__XXXXX__\   Copyright (C) 2020 - Nii-sanHax0r
/   XXX   \
     V
 \n";
}
if (!$argv[1]) {
	banner();
	echo "Usage : php index [ip/cidr]\n";
	echo "Ex    : php index 127.0.0.1/24";

}elseif($argv[1]){

	banner();
	echo "Result\n===========\n";
	$data = $argv[1];
	dataip($data);
}
?>